#!/usr/bin/env python3
"""Generate OpenWrt Makefile for CUPS 2.4.16 with proper tab indentation."""
import sys

output = sys.argv[1] if len(sys.argv) > 1 else "Makefile"

T = "\t"

lines = [
    "#",
    "# OpenWrt Makefile for CUPS 2.4.16",
    "#",
    "",
    "include $(TOPDIR)/rules.mk",
    "",
    "PKG_NAME:=cups",
    "PKG_VERSION:=2.4.16",
    "PKG_RELEASE:=1",
    "",
    "PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)-source.tar.gz",
    "PKG_SOURCE_URL:=https://github.com/OpenPrinting/cups/releases/download/v$(PKG_VERSION)",
    "PKG_HASH:=skip",
    "",
    "TARGET_LDFLAGS+=-Wl,-rpath-link=$(STAGING_DIR)/usr/lib",
    "",
    "include $(INCLUDE_DIR)/package.mk",
    "",
    "define Package/cups/Default",
    " URL:=http://www.cups.org/",
    " SUBMENU:=Printing",
    "endef",
    "",
    "define Package/cups",
    "$(call Package/cups/Default)",
    " SECTION:=net",
    " CATEGORY:=Network",
    " DEPENDS:=+libcups +libusb-1.0 +libstdcpp",
    " TITLE:=Common UNIX Printing System (daemon)",
    "endef",
    "",
    "define Package/cups/description",
    " Common UNIX Printing System (daemon) - version 2.4.16",
    "endef",
    "",
    "define Package/cups/conffiles",
    "/etc/cups/classes.conf",
    "/etc/cups/cupsd.conf",
    "/etc/cups/printers.conf",
    "endef",
    "",
    "define Package/cups-bsd",
    "$(call Package/cups/Default)",
    " SECTION:=net",
    " CATEGORY:=Network",
    " DEPENDS:=+libcups",
    " TITLE:=Common UNIX Printing System - BSD commands (old)",
    "endef",
    "",
    "define Package/cups-bsd/description",
    " Common UNIX Printing System - BSD commands (old)",
    "endef",
    "",
    "define Package/cups-client",
    "$(call Package/cups/Default)",
    " SECTION:=net",
    " CATEGORY:=Network",
    " DEPENDS:=+libcups +libcupsimage",
    " TITLE:=Common UNIX Printing System - Client commands",
    "endef",
    "",
    "define Package/cups-client/conffiles",
    "/etc/cups/client.conf",
    "endef",
    "",
    "define Package/cups-client/description",
    " Common UNIX Printing System - Client commands",
    "endef",
    "",
    "define Package/cups-filters",
    "$(call Package/cups/Default)",
    " SECTION:=net",
    " CATEGORY:=Network",
    " DEPENDS:=+libcupsimage",
    " TITLE:=Common UNIX Printing System - Filter",
    "endef",
    "",
    "define Package/cups-filters/description",
    " Common UNIX Printing System - Filter",
    "endef",
    "",
    "define Package/cups-ppdc",
    "$(call Package/cups/Default)",
    " SECTION:=net",
    " CATEGORY:=Network",
    " DEPENDS:=+libcups +zlib +libpthread +libpng +libjpeg +libstdcpp",
    " TITLE:=Common UNIX Printing System - PPDC utils",
    "endef",
    "",
    "define Package/cups-ppdc/description",
    " Common UNIX Printing System - PPDC utils",
    "endef",
    "",
    "define Package/libcups",
    "$(call Package/cups/Default)",
    " SECTION:=libs",
    " CATEGORY:=Libraries",
    " DEPENDS:=+zlib +libpthread +libpng +libjpeg",
    " TITLE:=Common UNIX Printing System - Core library",
    "endef",
    "",
    "define Package/libcups/description",
    " Common UNIX Printing System - Core library",
    "endef",
    "",
    "define Package/libcupsimage",
    "$(call Package/cups/Default)",
    " SECTION:=libs",
    " CATEGORY:=Libraries",
    " DEPENDS:=+libcups",
    " TITLE:=Common UNIX Printing System - Image library",
    "endef",
    "",
    "define Package/libcupsimage/description",
    " Common UNIX Printing System - Image library",
    "endef",
    "",
    "define Build/Configure",
    T + "$(call Build/Configure/Default, \\",
    T + "--with-cups-user=\"nobody\" \\",
    T + "--with-cups-group=\"nogroup\" \\",
    T + "--with-system-groups=\"root\" \\",
    T + "--with-pdftops=\"none\" \\",
    T + "--with-tls=no \\",
    T + "--without-perl \\",
    T + "--without-python \\",
    T + "--without-php \\",
    T + "--enable-default-shared \\",
    T + "--enable-shared \\",
    T + "--enable-image \\",
    T + "--enable-libusb \\",
    T + "--disable-acl \\",
    T + "--disable-dnssd \\",
    T + "--disable-dbus \\",
    T + "--disable-avahi \\",
    T + "--disable-launchd \\",
    T + "--disable-ldap \\",
    T + "--disable-pam \\",
    T + "--disable-slp \\",
    T + "--disable-gssapi \\",
    T + "--disable-tiff, \\",
    T + "UNAME=\"Linux\" \\",
    T + "LIBS=\"$(TARGET_LDFLAGS) -lz -lpng -ljpeg\" \\",
    T + ")",
    "endef",
    "",
    "define Build/Compile",
    T + "$(MAKE) -C $(PKG_BUILD_DIR) \\",
    T + "$(TARGET_CONFIGURE_OPTS) \\",
    T + "DSTROOT=\"$(PKG_INSTALL_DIR)\" \\",
    T + "STRIP=\"/bin/true\" \\",
    T + "all install",
    "endef",
    "",
    "define Package/cups/install",
    T + "rm -rf $(1)/etc/cups",
    T + "$(INSTALL_DIR) $(1)/etc/cups",
    T + "$(CP) $(PKG_INSTALL_DIR)/etc/cups/* $(1)/etc/cups/",
    T + "rm -rf $(1)/etc/cups/certs",
    T + "ln -sf /tmp $(1)/etc/cups/certs",
    T + "rm -f $(1)/usr/bin/cups-config",
    T + "$(INSTALL_DIR) $(1)/usr/lib/cups",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/backend $(1)/usr/lib/cups",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/cgi-bin $(1)/usr/lib/cups",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/daemon $(1)/usr/lib/cups",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/driver $(1)/usr/lib/cups",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/monitor $(1)/usr/lib/cups",
    T + "$(INSTALL_DIR) $(1)/usr/share/cups/templates",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/share/cups/templates/*.tmpl $(1)/usr/share/cups/templates/",
    T + "$(INSTALL_DIR) $(1)/usr/share/cups/mime",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/share/cups/mime/* $(1)/usr/share/cups/mime/",
    T + "$(INSTALL_DIR) $(1)/usr/share/doc/cups",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/share/doc/cups/*.*html $(1)/usr/share/doc/cups/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/share/doc/cups/*.css $(1)/usr/share/doc/cups/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/share/doc/cups/*.txt $(1)/usr/share/doc/cups/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/share/doc/cups/images $(1)/usr/share/doc/cups/",
    T + "$(INSTALL_DIR) $(1)/usr/sbin",
    T + "if [ -d ./files/etc/cups ]; then $(CP) ./files/etc/cups/* $(1)/etc/cups/; fi",
    T + "$(INSTALL_DIR) $(1)/etc/init.d",
    T + "if [ -f ./files/cupsd.init ]; then $(INSTALL_BIN) ./files/cupsd.init $(1)/etc/init.d/cupsd; fi",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/cupsctl $(1)/usr/sbin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/cupsd $(1)/usr/sbin/",
    T + "chmod 700 $(1)/usr/lib/cups/backend/usb",
    "endef",
    "",
    "define Package/cups-bsd/install",
    T + "$(INSTALL_DIR) $(1)/usr/bin",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/lprm $(1)/usr/bin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/lpq $(1)/usr/bin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/lpr $(1)/usr/bin/",
    T + "$(INSTALL_DIR) $(1)/usr/sbin",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/lpc $(1)/usr/sbin/",
    "endef",
    "",
    "define Package/cups-client/install",
    T + "$(INSTALL_DIR) $(1)/usr/bin",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/lp $(1)/usr/bin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/cancel $(1)/usr/bin/",
    T + "-$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/cupstestppd $(1)/usr/bin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/ipptool $(1)/usr/bin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/lpoptions $(1)/usr/bin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/lpstat $(1)/usr/bin/",
    T + "$(INSTALL_DIR) $(1)/usr/sbin",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/cupsaccept $(1)/usr/sbin/",
    T + "-$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/cupsfilter $(1)/usr/sbin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/lpadmin $(1)/usr/sbin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/lpinfo $(1)/usr/sbin/",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/lpmove $(1)/usr/sbin/",
    T + "(cd $(1)/usr/sbin; ln -sf cupsaccept accept; ln -sf cupsaccept cupsenable; ln -sf cupsaccept cupsdisable; ln -sf cupsaccept reject; ln -sf cupsaccept cupsreject;)",
    "endef",
    "",
    "define Package/cups-filters/install",
    T + "$(INSTALL_DIR) $(1)/usr/lib/cups/filter",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/filter/commandtops $(1)/usr/lib/cups/filter/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/filter/gziptoany $(1)/usr/lib/cups/filter/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/filter/pstops $(1)/usr/lib/cups/filter/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/filter/rastertoepson $(1)/usr/lib/cups/filter/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/filter/rastertohp $(1)/usr/lib/cups/filter/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/filter/rastertolabel $(1)/usr/lib/cups/filter/",
    T + "-$(CP) $(PKG_INSTALL_DIR)/usr/lib/cups/filter/rastertopwg $(1)/usr/lib/cups/filter/",
    T + "if [ -f $(1)/usr/lib/cups/filter/rastertolabel ]; then (cd $(1)/usr/lib/cups/filter; ln -sf rastertolabel rastertodymo;) fi",
    "endef",
    "",
    "define Package/cups-ppdc/install",
    T + "$(INSTALL_DIR) $(1)/usr/bin",
    T + "-$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/ppdc $(1)/usr/bin/",
    T + "-$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/ppdhtml $(1)/usr/bin/",
    T + "-$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/ppdi $(1)/usr/bin/",
    T + "-$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/ppdmerge $(1)/usr/bin/",
    T + "-$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/ppdpo $(1)/usr/bin/",
    "endef",
    "",
    "define Package/libcups/install",
    T + "$(INSTALL_DIR) $(1)/usr/lib",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/lib/libcups.so* $(1)/usr/lib/",
    "endef",
    "",
    "define Package/libcupsimage/install",
    T + "$(INSTALL_DIR) $(1)/usr/lib",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/lib/libcupsimage.so* $(1)/usr/lib/",
    "endef",
    "",
    "define Build/InstallDev",
    T + "$(INSTALL_DIR) $(2)/bin",
    T + "$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/cups-config $(2)/bin/",
    T + "$(INSTALL_DIR) $(1)/usr/include",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/include/cups $(1)/usr/include/",
    T + "$(INSTALL_DIR) $(1)/usr/lib",
    T + "$(CP) $(PKG_INSTALL_DIR)/usr/lib/libcups*.so* $(1)/usr/lib/",
    "endef",
    "",
    "$(eval $(call BuildPackage,cups))",
    "$(eval $(call BuildPackage,libcups))",
    "$(eval $(call BuildPackage,libcupsimage))",
    "$(eval $(call BuildPackage,cups-bsd))",
    "$(eval $(call BuildPackage,cups-client))",
    "$(eval $(call BuildPackage,cups-filters))",
    "$(eval $(call BuildPackage,cups-ppdc))",
]

with open(output, "w", newline="\n") as f:
    for line in lines:
        f.write(line + "\n")

print("Generated " + output + " with proper tab indentation")
